name: first
on: 
  push

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step0
      uses: actions/checkout@v4
    - name: step1
      run: sudo apt install libsdl2-dev libsdl2-ttf-dev
    - name: step2
      run: ./CMakeGCC.sh
    - name: step3
      run: |
        cd ./bin/make/
        make
    - name: step4
      run: |
        find .
        ./bin/make/Release/sobel
        

