name: first
on: 
  push

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step0
      uses: actions/checkout@v4
    - name: step1
      run: |
        git fetch 
        ./CMakeGCC.sh
