name: first
on: 
  push

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step0
      uses: actions/checkout@v4
    - name: step1
      run: |
        sudo apt install libsdl2-dev libsdl2-ttf-dev
        ./CMakeGCC.sh
        cmake ./bin/make/
        ls ./Release
        ./Release/Sobel

